/**
 * [INPUT]: 依赖 wrangler types 生成的 ASSETS 绑定及 workers-types 的 Fetcher 全局类型
 * [OUTPUT]: 对外提供 Cloudflare.Env 与 Env 的静态资源绑定类型声明
 * [POS]: src 的 Workers 类型边界，与运行时全局声明分离；绑定结构仍由 Wrangler 生成
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/cloudflare-env.d.ts` (hash: 4f9fe9ddb2ea1e2c41e1be5910da8551)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
