/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DirectoryRouteImport } from './routes/_directory'
import { Route as OgDotpngRouteImport } from './routes/og[.]png'
import { Route as DirectoryChar123LocaleChar125RouteImport } from './routes/_directory.{-$locale}'
import { Route as Char123LocaleChar125OgWorkbenchRouteImport } from './routes/{-$locale}.og-workbench'
import { Route as DirectoryChar123LocaleChar125IndexRouteImport } from './routes/_directory.{-$locale}.index'
import { Route as DirectoryChar123LocaleChar125NewsRouteImport } from './routes/_directory.{-$locale}.news'
import { Route as DirectoryChar123LocaleChar125SavedRouteImport } from './routes/_directory.{-$locale}.saved'
import { Route as DirectoryChar123LocaleChar125Top100RouteImport } from './routes/_directory.{-$locale}.top100'
import { Route as ApiOgSiteRouteImport } from './routes/api.og.site'
import { Route as Char123LocaleChar125NewsIdRouteImport } from './routes/{-$locale}.news.$id'
import { Route as DirectoryChar123LocaleChar125CategoryCategoryRouteImport } from './routes/_directory.{-$locale}.category.$category'
import { Route as Char123LocaleChar125ProjectsOwnerRepoRouteImport } from './routes/{-$locale}.projects.$owner.$repo'
import { Route as DirectoryChar123LocaleChar125PreviewOwnerRepoRouteImport } from './routes/_directory.{-$locale}.preview.$owner.$repo'
import { Route as ApiOgProjectsOwnerRepoRouteImport } from './routes/api.og.projects.$owner.$repo'

const DirectoryRoute = DirectoryRouteImport.update({
  id: '/_directory',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDotpngRoute = OgDotpngRouteImport.update({
  id: '/og.png',
  path: '/og.png',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryChar123LocaleChar125Route =
  DirectoryChar123LocaleChar125RouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => DirectoryRoute,
  } as any)
const Char123LocaleChar125OgWorkbenchRoute =
  Char123LocaleChar125OgWorkbenchRouteImport.update({
    id: '/{-$locale}/og-workbench',
    path: '/{-$locale}/og-workbench',
    getParentRoute: () => rootRouteImport,
  } as any)
const DirectoryChar123LocaleChar125IndexRoute =
  DirectoryChar123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DirectoryChar123LocaleChar125Route,
  } as any)
const DirectoryChar123LocaleChar125NewsRoute =
  DirectoryChar123LocaleChar125NewsRouteImport.update({
    id: '/news',
    path: '/news',
    getParentRoute: () => DirectoryChar123LocaleChar125Route,
  } as any)
const DirectoryChar123LocaleChar125SavedRoute =
  DirectoryChar123LocaleChar125SavedRouteImport.update({
    id: '/saved',
    path: '/saved',
    getParentRoute: () => DirectoryChar123LocaleChar125Route,
  } as any)
const DirectoryChar123LocaleChar125Top100Route =
  DirectoryChar123LocaleChar125Top100RouteImport.update({
    id: '/top100',
    path: '/top100',
    getParentRoute: () => DirectoryChar123LocaleChar125Route,
  } as any)
const ApiOgSiteRoute = ApiOgSiteRouteImport.update({
  id: '/api/og/site',
  path: '/api/og/site',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125NewsIdRoute =
  Char123LocaleChar125NewsIdRouteImport.update({
    id: '/{-$locale}/news/$id',
    path: '/{-$locale}/news/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const DirectoryChar123LocaleChar125CategoryCategoryRoute =
  DirectoryChar123LocaleChar125CategoryCategoryRouteImport.update({
    id: '/category/$category',
    path: '/category/$category',
    getParentRoute: () => DirectoryChar123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ProjectsOwnerRepoRoute =
  Char123LocaleChar125ProjectsOwnerRepoRouteImport.update({
    id: '/{-$locale}/projects/$owner/$repo',
    path: '/{-$locale}/projects/$owner/$repo',
    getParentRoute: () => rootRouteImport,
  } as any)
const DirectoryChar123LocaleChar125PreviewOwnerRepoRoute =
  DirectoryChar123LocaleChar125PreviewOwnerRepoRouteImport.update({
    id: '/preview/$owner/$repo',
    path: '/preview/$owner/$repo',
    getParentRoute: () => DirectoryChar123LocaleChar125Route,
  } as any)
const ApiOgProjectsOwnerRepoRoute = ApiOgProjectsOwnerRepoRouteImport.update({
  id: '/api/og/projects/$owner/$repo',
  path: '/api/og/projects/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DirectoryRouteWithChildren
  '/og.png': typeof OgDotpngRoute
  '/{-$locale}': typeof DirectoryChar123LocaleChar125RouteWithChildren
  '/{-$locale}/og-workbench': typeof Char123LocaleChar125OgWorkbenchRoute
  '/{-$locale}/news': typeof DirectoryChar123LocaleChar125NewsRoute
  '/{-$locale}/saved': typeof DirectoryChar123LocaleChar125SavedRoute
  '/{-$locale}/top100': typeof DirectoryChar123LocaleChar125Top100Route
  '/api/og/site': typeof ApiOgSiteRoute
  '/{-$locale}/news/$id': typeof Char123LocaleChar125NewsIdRoute
  '/{-$locale}/': typeof DirectoryChar123LocaleChar125IndexRoute
  '/{-$locale}/category/$category': typeof DirectoryChar123LocaleChar125CategoryCategoryRoute
  '/{-$locale}/projects/$owner/$repo': typeof Char123LocaleChar125ProjectsOwnerRepoRoute
  '/{-$locale}/preview/$owner/$repo': typeof DirectoryChar123LocaleChar125PreviewOwnerRepoRoute
  '/api/og/projects/$owner/$repo': typeof ApiOgProjectsOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof DirectoryRouteWithChildren
  '/og.png': typeof OgDotpngRoute
  '/{-$locale}/og-workbench': typeof Char123LocaleChar125OgWorkbenchRoute
  '/{-$locale}/news': typeof DirectoryChar123LocaleChar125NewsRoute
  '/{-$locale}/saved': typeof DirectoryChar123LocaleChar125SavedRoute
  '/{-$locale}/top100': typeof DirectoryChar123LocaleChar125Top100Route
  '/api/og/site': typeof ApiOgSiteRoute
  '/{-$locale}/news/$id': typeof Char123LocaleChar125NewsIdRoute
  '/{-$locale}': typeof DirectoryChar123LocaleChar125IndexRoute
  '/{-$locale}/category/$category': typeof DirectoryChar123LocaleChar125CategoryCategoryRoute
  '/{-$locale}/projects/$owner/$repo': typeof Char123LocaleChar125ProjectsOwnerRepoRoute
  '/{-$locale}/preview/$owner/$repo': typeof DirectoryChar123LocaleChar125PreviewOwnerRepoRoute
  '/api/og/projects/$owner/$repo': typeof ApiOgProjectsOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_directory': typeof DirectoryRouteWithChildren
  '/og.png': typeof OgDotpngRoute
  '/_directory/{-$locale}': typeof DirectoryChar123LocaleChar125RouteWithChildren
  '/{-$locale}/og-workbench': typeof Char123LocaleChar125OgWorkbenchRoute
  '/_directory/{-$locale}/news': typeof DirectoryChar123LocaleChar125NewsRoute
  '/_directory/{-$locale}/saved': typeof DirectoryChar123LocaleChar125SavedRoute
  '/_directory/{-$locale}/top100': typeof DirectoryChar123LocaleChar125Top100Route
  '/api/og/site': typeof ApiOgSiteRoute
  '/{-$locale}/news/$id': typeof Char123LocaleChar125NewsIdRoute
  '/_directory/{-$locale}/': typeof DirectoryChar123LocaleChar125IndexRoute
  '/_directory/{-$locale}/category/$category': typeof DirectoryChar123LocaleChar125CategoryCategoryRoute
  '/{-$locale}/projects/$owner/$repo': typeof Char123LocaleChar125ProjectsOwnerRepoRoute
  '/_directory/{-$locale}/preview/$owner/$repo': typeof DirectoryChar123LocaleChar125PreviewOwnerRepoRoute
  '/api/og/projects/$owner/$repo': typeof ApiOgProjectsOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/og.png'
    | '/{-$locale}'
    | '/{-$locale}/og-workbench'
    | '/{-$locale}/news'
    | '/{-$locale}/saved'
    | '/{-$locale}/top100'
    | '/api/og/site'
    | '/{-$locale}/news/$id'
    | '/{-$locale}/'
    | '/{-$locale}/category/$category'
    | '/{-$locale}/projects/$owner/$repo'
    | '/{-$locale}/preview/$owner/$repo'
    | '/api/og/projects/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/og.png'
    | '/{-$locale}/og-workbench'
    | '/{-$locale}/news'
    | '/{-$locale}/saved'
    | '/{-$locale}/top100'
    | '/api/og/site'
    | '/{-$locale}/news/$id'
    | '/{-$locale}'
    | '/{-$locale}/category/$category'
    | '/{-$locale}/projects/$owner/$repo'
    | '/{-$locale}/preview/$owner/$repo'
    | '/api/og/projects/$owner/$repo'
  id:
    | '__root__'
    | '/_directory'
    | '/og.png'
    | '/_directory/{-$locale}'
    | '/{-$locale}/og-workbench'
    | '/_directory/{-$locale}/news'
    | '/_directory/{-$locale}/saved'
    | '/_directory/{-$locale}/top100'
    | '/api/og/site'
    | '/{-$locale}/news/$id'
    | '/_directory/{-$locale}/'
    | '/_directory/{-$locale}/category/$category'
    | '/{-$locale}/projects/$owner/$repo'
    | '/_directory/{-$locale}/preview/$owner/$repo'
    | '/api/og/projects/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DirectoryRoute: typeof DirectoryRouteWithChildren
  OgDotpngRoute: typeof OgDotpngRoute
  Char123LocaleChar125OgWorkbenchRoute: typeof Char123LocaleChar125OgWorkbenchRoute
  ApiOgSiteRoute: typeof ApiOgSiteRoute
  Char123LocaleChar125NewsIdRoute: typeof Char123LocaleChar125NewsIdRoute
  Char123LocaleChar125ProjectsOwnerRepoRoute: typeof Char123LocaleChar125ProjectsOwnerRepoRoute
  ApiOgProjectsOwnerRepoRoute: typeof ApiOgProjectsOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_directory': {
      id: '/_directory'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og.png': {
      id: '/og.png'
      path: '/og.png'
      fullPath: '/og.png'
      preLoaderRoute: typeof OgDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_directory/{-$locale}': {
      id: '/_directory/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof DirectoryChar123LocaleChar125RouteImport
      parentRoute: typeof DirectoryRoute
    }
    '/{-$locale}/og-workbench': {
      id: '/{-$locale}/og-workbench'
      path: '/{-$locale}/og-workbench'
      fullPath: '/{-$locale}/og-workbench'
      preLoaderRoute: typeof Char123LocaleChar125OgWorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_directory/{-$locale}/': {
      id: '/_directory/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof DirectoryChar123LocaleChar125IndexRouteImport
      parentRoute: typeof DirectoryChar123LocaleChar125Route
    }
    '/_directory/{-$locale}/news': {
      id: '/_directory/{-$locale}/news'
      path: '/news'
      fullPath: '/{-$locale}/news'
      preLoaderRoute: typeof DirectoryChar123LocaleChar125NewsRouteImport
      parentRoute: typeof DirectoryChar123LocaleChar125Route
    }
    '/_directory/{-$locale}/saved': {
      id: '/_directory/{-$locale}/saved'
      path: '/saved'
      fullPath: '/{-$locale}/saved'
      preLoaderRoute: typeof DirectoryChar123LocaleChar125SavedRouteImport
      parentRoute: typeof DirectoryChar123LocaleChar125Route
    }
    '/_directory/{-$locale}/top100': {
      id: '/_directory/{-$locale}/top100'
      path: '/top100'
      fullPath: '/{-$locale}/top100'
      preLoaderRoute: typeof DirectoryChar123LocaleChar125Top100RouteImport
      parentRoute: typeof DirectoryChar123LocaleChar125Route
    }
    '/api/og/site': {
      id: '/api/og/site'
      path: '/api/og/site'
      fullPath: '/api/og/site'
      preLoaderRoute: typeof ApiOgSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/news/$id': {
      id: '/{-$locale}/news/$id'
      path: '/{-$locale}/news/$id'
      fullPath: '/{-$locale}/news/$id'
      preLoaderRoute: typeof Char123LocaleChar125NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_directory/{-$locale}/category/$category': {
      id: '/_directory/{-$locale}/category/$category'
      path: '/category/$category'
      fullPath: '/{-$locale}/category/$category'
      preLoaderRoute: typeof DirectoryChar123LocaleChar125CategoryCategoryRouteImport
      parentRoute: typeof DirectoryChar123LocaleChar125Route
    }
    '/{-$locale}/projects/$owner/$repo': {
      id: '/{-$locale}/projects/$owner/$repo'
      path: '/{-$locale}/projects/$owner/$repo'
      fullPath: '/{-$locale}/projects/$owner/$repo'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_directory/{-$locale}/preview/$owner/$repo': {
      id: '/_directory/{-$locale}/preview/$owner/$repo'
      path: '/preview/$owner/$repo'
      fullPath: '/{-$locale}/preview/$owner/$repo'
      preLoaderRoute: typeof DirectoryChar123LocaleChar125PreviewOwnerRepoRouteImport
      parentRoute: typeof DirectoryChar123LocaleChar125Route
    }
    '/api/og/projects/$owner/$repo': {
      id: '/api/og/projects/$owner/$repo'
      path: '/api/og/projects/$owner/$repo'
      fullPath: '/api/og/projects/$owner/$repo'
      preLoaderRoute: typeof ApiOgProjectsOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DirectoryChar123LocaleChar125RouteChildren {
  DirectoryChar123LocaleChar125NewsRoute: typeof DirectoryChar123LocaleChar125NewsRoute
  DirectoryChar123LocaleChar125SavedRoute: typeof DirectoryChar123LocaleChar125SavedRoute
  DirectoryChar123LocaleChar125Top100Route: typeof DirectoryChar123LocaleChar125Top100Route
  DirectoryChar123LocaleChar125IndexRoute: typeof DirectoryChar123LocaleChar125IndexRoute
  DirectoryChar123LocaleChar125CategoryCategoryRoute: typeof DirectoryChar123LocaleChar125CategoryCategoryRoute
  DirectoryChar123LocaleChar125PreviewOwnerRepoRoute: typeof DirectoryChar123LocaleChar125PreviewOwnerRepoRoute
}

const DirectoryChar123LocaleChar125RouteChildren: DirectoryChar123LocaleChar125RouteChildren =
  {
    DirectoryChar123LocaleChar125NewsRoute:
      DirectoryChar123LocaleChar125NewsRoute,
    DirectoryChar123LocaleChar125SavedRoute:
      DirectoryChar123LocaleChar125SavedRoute,
    DirectoryChar123LocaleChar125Top100Route:
      DirectoryChar123LocaleChar125Top100Route,
    DirectoryChar123LocaleChar125IndexRoute:
      DirectoryChar123LocaleChar125IndexRoute,
    DirectoryChar123LocaleChar125CategoryCategoryRoute:
      DirectoryChar123LocaleChar125CategoryCategoryRoute,
    DirectoryChar123LocaleChar125PreviewOwnerRepoRoute:
      DirectoryChar123LocaleChar125PreviewOwnerRepoRoute,
  }

const DirectoryChar123LocaleChar125RouteWithChildren =
  DirectoryChar123LocaleChar125Route._addFileChildren(
    DirectoryChar123LocaleChar125RouteChildren,
  )

interface DirectoryRouteChildren {
  DirectoryChar123LocaleChar125Route: typeof DirectoryChar123LocaleChar125RouteWithChildren
}

const DirectoryRouteChildren: DirectoryRouteChildren = {
  DirectoryChar123LocaleChar125Route:
    DirectoryChar123LocaleChar125RouteWithChildren,
}

const DirectoryRouteWithChildren = DirectoryRoute._addFileChildren(
  DirectoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DirectoryRoute: DirectoryRouteWithChildren,
  OgDotpngRoute: OgDotpngRoute,
  Char123LocaleChar125OgWorkbenchRoute: Char123LocaleChar125OgWorkbenchRoute,
  ApiOgSiteRoute: ApiOgSiteRoute,
  Char123LocaleChar125NewsIdRoute: Char123LocaleChar125NewsIdRoute,
  Char123LocaleChar125ProjectsOwnerRepoRoute:
    Char123LocaleChar125ProjectsOwnerRepoRoute,
  ApiOgProjectsOwnerRepoRoute: ApiOgProjectsOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
